# Generated by Django 3.2.5 on 2021-07-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_produto_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opcoes',
            old_name='acrecimo',
            new_name='acrescimo',
        ),
    ]
